language: scala
scala:
- 2.11.12
- 2.12.6
jdk:
- oraclejdk8
script:
- sbt test
deploy:
  skip_cleanup: true
  provider: script
  script: "./.travis/deploy.sh $TRAVIS_TAG"
  on:
    condition: '"${TRAVIS_SCALA_VERSION}" == "2.12.6"'
    tags: true
env:
  global:
    secure: iQlMhsIf1l60FHFNSXlB0MVu4FXeIm0YdZFVaaalP/V9cbEtMdpvBj0GxvQjEwNf4OG4LtHRVkRViE/f3fGr6oyN00dhoNY33yALbU5qd5OYTnIHa1deDFP95VZ/TTZUCp02hUqo7gPaSzi24cX0CzeJsEAD6YWDf25MhL30KglzAKpg1V+8sYg9wd+HR30Mheft/z4mJWurA+3xIsGLOHLtWTRaJZjWiRutWEH7VvzGzuTe/TGu9Li7SMxfjmytzOdC0q5cyVUA2dAPbWEi3h48RGSjMvsfGSqCDpJb9ME2QocNV8b7qtdOZFi3MQCdUFG+w4f1EofdwynfLwECjX9NbFbCtTRL+TPZkEyUwGpza3/mG1jTTJ7M8PtCN+YQhIAxPj/R1cWNj2etPcFBBBn79487MMTvAOhLJZb3rBIc6gJyJnFiJmAbY77EIOjSxN+64dV2/iaF7uaNve4qQPtGrObG9VVNhNSCMdxqOKHDwwa0AQlY/gtLTH362r1uOjijt9xOZXN8Q2ZHjSysnCAqBtTexNg7of5FMaPVodgS+9OkB7da6hjORItJLQkCkXqys1EakcIH3r9zN8I9xXbiHrxOWr2wJ4Ss8ZGZrhzaCguii86c6ceb3C3hxj2Fm1zgmtoXEFY1Tj3E5Aq33Z+Q3yvnSHQokKl/lLlXlQE=
