dist: trusty
language: scala
scala:
- 2.12.10
jdk:
- oraclejdk8
script:
- sbt test
deploy:
  skip_cleanup: true
  provider: script
  script: "./.travis/deploy.sh $TRAVIS_TAG"
  on:
    condition: '"${TRAVIS_SCALA_VERSION}" == "2.12.10"'
    tags: true
env:
  global:
  - secure: Dzw+1Ezi700FyCxkpvo5WIqX7Mk35dLZYh0P+Slsc6HMS5jJ0JnfmAUNV4vC2S6v7tQca2Ws0X8NFXmsAQX2yttNm8fIAAmovZjwXSeK/m1wA7wXTSyRGca/lDxDNpehApK4bTBk6UgUq5+jY8YmwB3Hf0Am8Y4G7oOOnw09yYptZcQaK2cOVgaKr+HIZ3xwGTO6G/FtPzOwRnUCrOIsTNtSDpMkH42Xp16f2TkjZfc40kOWCH5f3ppLoMvI/emtp3IuCJ5SWufkXQn2g8eDzawSh2E3UxaJtlZEbEdPUMnxYcf/zbWZ2wt9vUbtxGLw/lxHnr+Q4xMYn0SljJRbA2wg3U266yHNVGXcm4kOAhc17duShqPAi6D5hwCkYNbSBnydfpgC0MbM337MoyXlNZnOb9s5S6gZkmaXcUDv3GKz2S7SzlfypE44QY43XeP8MgL5dfMEM44YnMJC5HlQyT4RQuH0YzoWGtJ8r8jz+E51yC4XkjjQL5l22a24muyId3EwTUtaHsVSENmZqmGeYx6bc0/Aeb0lNaMXabgcLd/JJMlyfvtYxrbx5q4XQS6EbQHTU/raMllODXjjHroohoDqkGp3luqHl++YvX0QYUfbCgNLTPy0NoxR6KMMCAIGJOWJjPP0PjO4obmxjeam1mhGWw+8BYFYVfTpMHppSao=
  - secure: gcjR3294DR2ebEQjSNliK+NLRAbBUavDEbWMvsesEXZnwzpDHqH23Q0JnoFo0EnL9OwNtoc8TbSMCSMeO8xaVQUdPt9HhQQ7kG+24pDOg82V8MNXPH4BhRbKBxhUDfk2E82xUQhenDcMzoDVsLaie47+2t6bPlWvRZ8nOKyvMmPRe/2d1EU3UoPBLKqVoe4XZWQs3sRqEwe7WAs8A12HmvBRK7PMzdV487KZ46jBk97Tk3x/H/uaYQdhuRQZGtKNfU863kiVw3lq4VGmBAykr3b+qW33+phVpVxEOZAUUNy3Er7ZLEFczQG+9AO25PFQ3bY4jCcQ9MH6nMEhbmNYzhSfezmQ7dA8wnvIDUCwlo81NIv1sAxj4iXfHs0MICg600NDZIvVuZkUaV4YvRtQxeC/jWf68SyfZsXvX/WQYR2biUDeDynFo2KCs2WcKIm3Wr7Inird22S08yMi6lpCuz3TbcvD0+Wezc+gBu5qnBbTj8jlQivYG+gHXVcOBkc0JJ9Gmy3SSOICbGndhSRHxtFYAKXLP2dxpuXvgDKdA8Df0UBaArH+iLVlEEMKM5MNo6qaVZDyP6RvWOcn+C/vE85vTCPMXk23IU+lrKdQBybhKqRheO55DM0NbzEi1QRkmP38gb/wqieMBceXhLkld1LU4l+5AHpo5huOlkAF6QM=
  - secure: iQlMhsIf1l60FHFNSXlB0MVu4FXeIm0YdZFVaaalP/V9cbEtMdpvBj0GxvQjEwNf4OG4LtHRVkRViE/f3fGr6oyN00dhoNY33yALbU5qd5OYTnIHa1deDFP95VZ/TTZUCp02hUqo7gPaSzi24cX0CzeJsEAD6YWDf25MhL30KglzAKpg1V+8sYg9wd+HR30Mheft/z4mJWurA+3xIsGLOHLtWTRaJZjWiRutWEH7VvzGzuTe/TGu9Li7SMxfjmytzOdC0q5cyVUA2dAPbWEi3h48RGSjMvsfGSqCDpJb9ME2QocNV8b7qtdOZFi3MQCdUFG+w4f1EofdwynfLwECjX9NbFbCtTRL+TPZkEyUwGpza3/mG1jTTJ7M8PtCN+YQhIAxPj/R1cWNj2etPcFBBBn79487MMTvAOhLJZb3rBIc6gJyJnFiJmAbY77EIOjSxN+64dV2/iaF7uaNve4qQPtGrObG9VVNhNSCMdxqOKHDwwa0AQlY/gtLTH362r1uOjijt9xOZXN8Q2ZHjSysnCAqBtTexNg7of5FMaPVodgS+9OkB7da6hjORItJLQkCkXqys1EakcIH3r9zN8I9xXbiHrxOWr2wJ4Ss8ZGZrhzaCguii86c6ceb3C3hxj2Fm1zgmtoXEFY1Tj3E5Aq33Z+Q3yvnSHQokKl/lLlXlQE=
  - SONA_USER=snowplow
